### ISSUE TITLE
Proposta

### ISSUE THREAD

**Issue by TearPelato** [LIUKRAST/HemeraldProjectsCommunity#21]
potresti(come per la emi schematics mod che hai messo su cursforge) caricare la tom simple storage 1.20.1 l'edit che fa in modo che per usarla server l'elettricita?

**Comment by LIUKRAST** [comment]
Ciao! Per favore usa la repository apposita per [EMI: Create Schematics](https://github.com/LIUKRAST/EmiCreateSchematics/issues)

**Comment by LIUKRAST** [comment]
Ah scusa ho letto male. Mi spiace ma la tom simple storage mi è stata commissionata da hemerald e gli accordi erano di non pubblicarla, in quanto mi è stata pagata.
